config/routes.rb
Rails.application.routes.draw do
  # get "todos", to: "todos#index"
  # post "todos/create", to: "todos#create"
  # get "todos/:id", to: "todos#show"
  resources :todos
  post "/users/login", to: "users#login"
  resources :users
  root to: "pages#main"
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  validates :todo_text, presence: true
  validates :todo_text, length: { minimum: 2 }
  validates :due_date, presence: true

  def due_today?
    due_date == Date.today
  end

  def self.of_user(user)
    all.where(user_id: user.id)
  end

  def self.overdue_todos
    all.where("due_date < ? and (not completed)", Date.today)
  end

  def self.due_today_todos
    all.where("due_date = ?", Date.today)
  end

  def self.due_later_todos
    all.where("due_date > ?", Date.today)
  end

  def self.completed_todos
    all.where(completed: true)
  end

  def self.add_task(task)
    create!(todo_text: task[:todo_text], due_date: Date.today + task[:due_in_days], completed: false)
  end

  def self.mark_as_complete!(todo_id)
    todo = find(todo_id)
    todo.completed = true
    todo.save
    todo
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :todos
  validates :name, presence: true
  validates :name, length: { minimum: 2 }
  validates :email, presence: true

  def display_users_list
    "<li><a href=\"/users/#{id}\">#{name} - #{email}</a></li>"
  end

  def display_user
    "<h2>Details about #{name}:</h2><ul><li>Name: #{name}</li><li>Email: #{email}</li></ul>"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      # halt tht request cycle
      redirect_to "/"
    end
  end

  def current_user
    # memoization
    return @current_user if @current_user
    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def main
    if current_user
      redirect_to todos_path
    else
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to "/"
    else
      flash[:error] = "Your email/password is wrong!"
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
# todos_controller.rb
class TodosController < ApplicationController
  def index
    # @todos = Todo.of_user(current_user)
    @todos = current_user.todos
    render "index"
  end

  def show
    todo_id = params[:id]
    todo = Todo.of_user(current_user).find(todo_id)
    render plain: todo.to_pleasant_string
  end

  def create
    todo_text = params[:todo_text]
    due_date = params[:due_date]
    new_todo = Todo.new(
      todo_text: todo_text,
      due_date: due_date,
      completed: false,
      user_id: current_user.id,
    )

    if new_todo.save
      redirect_to todos_path
    else
      flash[:error] = new_todo.errors.full_messages.join(", ")
      redirect_to todos_path
    end
  end

  def update
    id = params[:id]
    completed = params[:completed]
    todo = Todo.of_user(current_user).find(id)
    todo.completed = completed
    todo.save!
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = Todo.of_user(current_user).find(id)
    todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    render "new"
  end

  def index
    users_list = User.all.map { |user| user.display_users_list }.join("")
    to_render = "<h2>List of users on our platform!</h2><ol>#{users_list}</ol>"
    render html: to_render.html_safe
  end

  def create
    name = params[:name]
    email = params[:email]
    password = params[:password]
    user = User.new(
      name: name,
      email: email,
      password: password,
    )
    if user.save
      session[:current_user_id] = user.id
      redirect_to todos_path
    else
      flash[:error] = user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end

  def show
    id = params[:id]
    user = User.find(id)
    to_render = "#{user.display_user}<p><a href=\"/users\">All Users</a></p>"
    render html: to_render.html_safe
  end

  def login
    email = params[:email]
    password = params[:password]
    user = User.find_by(email: email, password: password)
    to_render = not(user == nil)
    render plain: to_render.to_s
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user %>
      <h3 class="userHeader">
        Welcome, <%= @current_user.name %>!
        <span class="userHeader-signout"><%= link_to "Sign out", destroy_session_path, method: "delete" %></span>
      </h3>
    <%end%>
    <% if flash[:error] %>
      <p class="flash-error">
        <%= flash[:error] %>
      </p>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1 class="TodoPage-title">Welcome to Todo Manager!</h1>
<h3 class="Home-navigation">If new user, <%= link_to "Sign-up here!", new_user_path %></h3>
<h3 class="Home-navigation">If existing user, <%= link_to "Sign-in here!", new_sessions_path %></h3>

app/views/todos/_todo-list.html.erb
<section class="TodoSection">
  <h2 class="TodoSection-title">
    <%= label %> <span class="TodoSection-title--info">
    <%if show_remaining %>
      <%= todos.completed_todos.length %> /
    <%end%>
    <%= todos.length %></span>
  </h2>
  <% todos.each do |todo| %>
  <div class="TodoSection-item">
    <%= form_with url: "/todos/#{todo.id}", method: "PUT" do %>
      <label class="TodoSection-todo <%= todo.completed ? "TodoSection-todo-completed" : nil %>">
        <%= check_box_tag 'completed', 'isCompleted', todo.completed, onclick: "this.form.submit()" %>
        <%= todo.todo_text %>
      </label>
    <% end %>
    <% if show_due_date %>
    <span class="TodoLabel"><%= todo.due_date.to_s(:short) %></span>
    <%end%>
    <%= form_with url: "/todos/#{todo.id}", method: "DELETE" do %>
      <%= image_submit_tag "trash.png", class:"TodoAction-delete" %>
    <% end %>
  </div>
<% end %>
</section>

app/views/todos/index.html.erb
<h1 class="TodoPage-title">My To-do List</h1>
<%= form_with url: "/todos", method: "POST", class:"AddTodo-form" do %>
  <%= text_field_tag 'todo_text', nil, class: 'AddTodo-input', placeholder: "What's next?" %>
  <%= date_field_tag 'due_date', nil, class: 'AddTodo-input' %>
  <%= submit_tag "Add", class: "AddTodo-input AddTodo-input--submit" %>
<%end%>
<article>
  <%= render partial: "todo-list", locals: {
    todos: @todos.overdue_todos.order(:due_date),
    label: "Overdue",
    show_due_date: true,
    show_remaining: false
  } %>
  <%= render partial: "todo-list", locals: {
    todos: @todos.due_today_todos.order(:due_date),
    label: "Due Today",
    show_due_date: false,
    show_remaining: true
  } %>
  <%= render partial: "todo-list", locals: {
    todos: @todos.due_later_todos.order(:due_date),
    label: "Due Later",
    show_due_date: true,
    show_remaining: true
  } %>
</article>

app/views/users/new.html.erb
<h1 class="TodoPage-title UserAuth-title">New here? Let's get you signed up!</h1>
<%= form_with url: users_path, class: "UserAuth-form" do |form| %>
  <div class="UserAuth-input-container">
    <%= form.text_field :name, placeholder: "Your name", class: "UserAuth-input" %>
    <p class="UserAuth-label">Your Name</p>
  </div>
  <div class="UserAuth-input-container">
    <%= form.email_field :email, placeholder: "Your email", class: "UserAuth-input" %>
    <p class="UserAuth-label">Your email</p>
  </div>
  <div class="UserAuth-input-container">
    <%= form.password_field :password, placeholder: "A strong password", class: "UserAuth-input" %>
    <p class="UserAuth-label">A strong password</p>
  </div>
  <%= form.submit "Signup", class: "UserAuth-submit" %>
<%end%>